version: '3.8'
services:
  web:
    image: node:18
    working_dir: /app
    volumes:
      - ./frontend:/app/frontend
    command: bash -c "cd frontend && yarn install && yarn build"
  api:
    image: node:18
    working_dir: /app
    volumes:
      - ./backend:/app/backend
    command: bash -c "cd backend && yarn install && yarn start"
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: nrsgirls
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data: {}